version: '3.9'
name: goverland-datasource-snapshot-local
services:
  datasource:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/volumes/db-data/:/var/lib/postgresql/data/
