// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: userspb/users.proto

package userspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsersInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersInfoRequest) Reset() {
	*x = GetUsersInfoRequest{}
	mi := &file_userspb_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoRequest) ProtoMessage() {}

func (x *GetUsersInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUsersInfoRequest) Descriptor() ([]byte, []int) {
	return file_userspb_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersInfoRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	About         string                 `protobuf:"bytes,2,opt,name=about,proto3" json:"about,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_userspb_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_userspb_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserInfo) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

type GetUsersInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersInfoResponse) Reset() {
	*x = GetUsersInfoResponse{}
	mi := &file_userspb_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoResponse) ProtoMessage() {}

func (x *GetUsersInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUsersInfoResponse) Descriptor() ([]byte, []int) {
	return file_userspb_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersInfoResponse) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_userspb_users_proto protoreflect.FileDescriptor

const file_userspb_users_proto_rawDesc = "" +
	"\n" +
	"\x13userspb/users.proto\x12\auserspb\"3\n" +
	"\x13GetUsersInfoRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\":\n" +
	"\bUserInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05about\x18\x02 \x01(\tR\x05about\"=\n" +
	"\x14GetUsersInfoResponse\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.userspb.UserInfoR\x04list2T\n" +
	"\x05Users\x12K\n" +
	"\fGetUsersInfo\x12\x1c.userspb.GetUsersInfoRequest\x1a\x1d.userspb.GetUsersInfoResponseB\vZ\t./userspbb\x06proto3"

var (
	file_userspb_users_proto_rawDescOnce sync.Once
	file_userspb_users_proto_rawDescData []byte
)

func file_userspb_users_proto_rawDescGZIP() []byte {
	file_userspb_users_proto_rawDescOnce.Do(func() {
		file_userspb_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userspb_users_proto_rawDesc), len(file_userspb_users_proto_rawDesc)))
	})
	return file_userspb_users_proto_rawDescData
}

var file_userspb_users_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_userspb_users_proto_goTypes = []any{
	(*GetUsersInfoRequest)(nil),  // 0: userspb.GetUsersInfoRequest
	(*UserInfo)(nil),             // 1: userspb.UserInfo
	(*GetUsersInfoResponse)(nil), // 2: userspb.GetUsersInfoResponse
}
var file_userspb_users_proto_depIdxs = []int32{
	1, // 0: userspb.GetUsersInfoResponse.list:type_name -> userspb.UserInfo
	0, // 1: userspb.Users.GetUsersInfo:input_type -> userspb.GetUsersInfoRequest
	2, // 2: userspb.Users.GetUsersInfo:output_type -> userspb.GetUsersInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_userspb_users_proto_init() }
func file_userspb_users_proto_init() {
	if File_userspb_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userspb_users_proto_rawDesc), len(file_userspb_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userspb_users_proto_goTypes,
		DependencyIndexes: file_userspb_users_proto_depIdxs,
		MessageInfos:      file_userspb_users_proto_msgTypes,
	}.Build()
	File_userspb_users_proto = out.File
	file_userspb_users_proto_goTypes = nil
	file_userspb_users_proto_depIdxs = nil
}
