// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: delegatepb/delegate.proto

package delegatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelegateEntry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Address              string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	DelegatorCount       int32                  `protobuf:"varint,2,opt,name=delegator_count,json=delegatorCount,proto3" json:"delegator_count,omitempty"`
	PercentOfDelegators  float64                `protobuf:"fixed64,3,opt,name=percent_of_delegators,json=percentOfDelegators,proto3" json:"percent_of_delegators,omitempty"`
	VotingPower          float64                `protobuf:"fixed64,4,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	PercentOfVotingPower float64                `protobuf:"fixed64,5,opt,name=percent_of_voting_power,json=percentOfVotingPower,proto3" json:"percent_of_voting_power,omitempty"`
	About                string                 `protobuf:"bytes,6,opt,name=about,proto3" json:"about,omitempty"`
	Statement            string                 `protobuf:"bytes,7,opt,name=statement,proto3" json:"statement,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DelegateEntry) Reset() {
	*x = DelegateEntry{}
	mi := &file_delegatepb_delegate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateEntry) ProtoMessage() {}

func (x *DelegateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateEntry.ProtoReflect.Descriptor instead.
func (*DelegateEntry) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{0}
}

func (x *DelegateEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DelegateEntry) GetDelegatorCount() int32 {
	if x != nil {
		return x.DelegatorCount
	}
	return 0
}

func (x *DelegateEntry) GetPercentOfDelegators() float64 {
	if x != nil {
		return x.PercentOfDelegators
	}
	return 0
}

func (x *DelegateEntry) GetVotingPower() float64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

func (x *DelegateEntry) GetPercentOfVotingPower() float64 {
	if x != nil {
		return x.PercentOfVotingPower
	}
	return 0
}

func (x *DelegateEntry) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *DelegateEntry) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type GetDelegatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoOriginalId string                 `protobuf:"bytes,1,opt,name=dao_original_id,json=daoOriginalId,proto3" json:"dao_original_id,omitempty"`
	Strategy      *anypb.Any             `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Addresses     []string               `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Sort          *string                `protobuf:"bytes,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatesRequest) Reset() {
	*x = GetDelegatesRequest{}
	mi := &file_delegatepb_delegate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesRequest) ProtoMessage() {}

func (x *GetDelegatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesRequest.ProtoReflect.Descriptor instead.
func (*GetDelegatesRequest) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{1}
}

func (x *GetDelegatesRequest) GetDaoOriginalId() string {
	if x != nil {
		return x.DaoOriginalId
	}
	return ""
}

func (x *GetDelegatesRequest) GetStrategy() *anypb.Any {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *GetDelegatesRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetDelegatesRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

func (x *GetDelegatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDelegatesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetDelegatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegates     []*DelegateEntry       `protobuf:"bytes,1,rep,name=delegates,proto3" json:"delegates,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatesResponse) Reset() {
	*x = GetDelegatesResponse{}
	mi := &file_delegatepb_delegate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesResponse) ProtoMessage() {}

func (x *GetDelegatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesResponse.ProtoReflect.Descriptor instead.
func (*GetDelegatesResponse) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{2}
}

func (x *GetDelegatesResponse) GetDelegates() []*DelegateEntry {
	if x != nil {
		return x.Delegates
	}
	return nil
}

func (x *GetDelegatesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetDelegateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoOriginalId string                 `protobuf:"bytes,1,opt,name=dao_original_id,json=daoOriginalId,proto3" json:"dao_original_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Strategy      *anypb.Any             `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegateProfileRequest) Reset() {
	*x = GetDelegateProfileRequest{}
	mi := &file_delegatepb_delegate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegateProfileRequest) ProtoMessage() {}

func (x *GetDelegateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegateProfileRequest.ProtoReflect.Descriptor instead.
func (*GetDelegateProfileRequest) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{3}
}

func (x *GetDelegateProfileRequest) GetDaoOriginalId() string {
	if x != nil {
		return x.DaoOriginalId
	}
	return ""
}

func (x *GetDelegateProfileRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDelegateProfileRequest) GetStrategy() *anypb.Any {
	if x != nil {
		return x.Strategy
	}
	return nil
}

type GetDelegateProfileResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Address              string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	VotingPower          float64                `protobuf:"fixed64,2,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	IncomingPower        float64                `protobuf:"fixed64,3,opt,name=incoming_power,json=incomingPower,proto3" json:"incoming_power,omitempty"`
	OutgoingPower        float64                `protobuf:"fixed64,4,opt,name=outgoing_power,json=outgoingPower,proto3" json:"outgoing_power,omitempty"`
	PercentOfVotingPower float64                `protobuf:"fixed64,5,opt,name=percent_of_voting_power,json=percentOfVotingPower,proto3" json:"percent_of_voting_power,omitempty"`
	PercentOfDelegators  float64                `protobuf:"fixed64,6,opt,name=percent_of_delegators,json=percentOfDelegators,proto3" json:"percent_of_delegators,omitempty"`
	Delegates            []*ProfileDelegateItem `protobuf:"bytes,7,rep,name=delegates,proto3" json:"delegates,omitempty"`
	Expiration           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetDelegateProfileResponse) Reset() {
	*x = GetDelegateProfileResponse{}
	mi := &file_delegatepb_delegate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegateProfileResponse) ProtoMessage() {}

func (x *GetDelegateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegateProfileResponse.ProtoReflect.Descriptor instead.
func (*GetDelegateProfileResponse) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{4}
}

func (x *GetDelegateProfileResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDelegateProfileResponse) GetVotingPower() float64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetIncomingPower() float64 {
	if x != nil {
		return x.IncomingPower
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetOutgoingPower() float64 {
	if x != nil {
		return x.OutgoingPower
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetPercentOfVotingPower() float64 {
	if x != nil {
		return x.PercentOfVotingPower
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetPercentOfDelegators() float64 {
	if x != nil {
		return x.PercentOfDelegators
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetDelegates() []*ProfileDelegateItem {
	if x != nil {
		return x.Delegates
	}
	return nil
}

func (x *GetDelegateProfileResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type ProfileDelegateItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Weight         float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	DelegatedPower float64                `protobuf:"fixed64,3,opt,name=delegated_power,json=delegatedPower,proto3" json:"delegated_power,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileDelegateItem) Reset() {
	*x = ProfileDelegateItem{}
	mi := &file_delegatepb_delegate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileDelegateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileDelegateItem) ProtoMessage() {}

func (x *ProfileDelegateItem) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileDelegateItem.ProtoReflect.Descriptor instead.
func (*ProfileDelegateItem) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileDelegateItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProfileDelegateItem) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProfileDelegateItem) GetDelegatedPower() float64 {
	if x != nil {
		return x.DelegatedPower
	}
	return 0
}

type GetDelegatesStatementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoOriginalId string                 `protobuf:"bytes,1,opt,name=dao_original_id,json=daoOriginalId,proto3" json:"dao_original_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatesStatementRequest) Reset() {
	*x = GetDelegatesStatementRequest{}
	mi := &file_delegatepb_delegate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesStatementRequest) ProtoMessage() {}

func (x *GetDelegatesStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesStatementRequest.ProtoReflect.Descriptor instead.
func (*GetDelegatesStatementRequest) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{6}
}

func (x *GetDelegatesStatementRequest) GetDaoOriginalId() string {
	if x != nil {
		return x.DaoOriginalId
	}
	return ""
}

func (x *GetDelegatesStatementRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type DelegateStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Statement     string                 `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateStatement) Reset() {
	*x = DelegateStatement{}
	mi := &file_delegatepb_delegate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateStatement) ProtoMessage() {}

func (x *DelegateStatement) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateStatement.ProtoReflect.Descriptor instead.
func (*DelegateStatement) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{7}
}

func (x *DelegateStatement) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DelegateStatement) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type GetDelegatesStatementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoOriginalId string                 `protobuf:"bytes,1,opt,name=dao_original_id,json=daoOriginalId,proto3" json:"dao_original_id,omitempty"`
	List          []*DelegateStatement   `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatesStatementResponse) Reset() {
	*x = GetDelegatesStatementResponse{}
	mi := &file_delegatepb_delegate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesStatementResponse) ProtoMessage() {}

func (x *GetDelegatesStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delegatepb_delegate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesStatementResponse.ProtoReflect.Descriptor instead.
func (*GetDelegatesStatementResponse) Descriptor() ([]byte, []int) {
	return file_delegatepb_delegate_proto_rawDescGZIP(), []int{8}
}

func (x *GetDelegatesStatementResponse) GetDaoOriginalId() string {
	if x != nil {
		return x.DaoOriginalId
	}
	return ""
}

func (x *GetDelegatesStatementResponse) GetList() []*DelegateStatement {
	if x != nil {
		return x.List
	}
	return nil
}

var File_delegatepb_delegate_proto protoreflect.FileDescriptor

const file_delegatepb_delegate_proto_rawDesc = "" +
	"\n" +
	"\x19delegatepb/delegate.proto\x12\n" +
	"delegatepb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x94\x02\n" +
	"\rDelegateEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12'\n" +
	"\x0fdelegator_count\x18\x02 \x01(\x05R\x0edelegatorCount\x122\n" +
	"\x15percent_of_delegators\x18\x03 \x01(\x01R\x13percentOfDelegators\x12!\n" +
	"\fvoting_power\x18\x04 \x01(\x01R\vvotingPower\x125\n" +
	"\x17percent_of_voting_power\x18\x05 \x01(\x01R\x14percentOfVotingPower\x12\x14\n" +
	"\x05about\x18\x06 \x01(\tR\x05about\x12\x1c\n" +
	"\tstatement\x18\a \x01(\tR\tstatement\"\xdd\x01\n" +
	"\x13GetDelegatesRequest\x12&\n" +
	"\x0fdao_original_id\x18\x01 \x01(\tR\rdaoOriginalId\x120\n" +
	"\bstrategy\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\bstrategy\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\tH\x00R\x04sort\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offsetB\a\n" +
	"\x05_sort\"e\n" +
	"\x14GetDelegatesResponse\x127\n" +
	"\tdelegates\x18\x01 \x03(\v2\x19.delegatepb.DelegateEntryR\tdelegates\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8f\x01\n" +
	"\x19GetDelegateProfileRequest\x12&\n" +
	"\x0fdao_original_id\x18\x01 \x01(\tR\rdaoOriginalId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x120\n" +
	"\bstrategy\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\bstrategy\"\x8d\x03\n" +
	"\x1aGetDelegateProfileResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12!\n" +
	"\fvoting_power\x18\x02 \x01(\x01R\vvotingPower\x12%\n" +
	"\x0eincoming_power\x18\x03 \x01(\x01R\rincomingPower\x12%\n" +
	"\x0eoutgoing_power\x18\x04 \x01(\x01R\routgoingPower\x125\n" +
	"\x17percent_of_voting_power\x18\x05 \x01(\x01R\x14percentOfVotingPower\x122\n" +
	"\x15percent_of_delegators\x18\x06 \x01(\x01R\x13percentOfDelegators\x12=\n" +
	"\tdelegates\x18\a \x03(\v2\x1f.delegatepb.ProfileDelegateItemR\tdelegates\x12:\n" +
	"\n" +
	"expiration\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\"p\n" +
	"\x13ProfileDelegateItem\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12'\n" +
	"\x0fdelegated_power\x18\x03 \x01(\x01R\x0edelegatedPower\"d\n" +
	"\x1cGetDelegatesStatementRequest\x12&\n" +
	"\x0fdao_original_id\x18\x01 \x01(\tR\rdaoOriginalId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\"K\n" +
	"\x11DelegateStatement\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\tstatement\x18\x02 \x01(\tR\tstatement\"z\n" +
	"\x1dGetDelegatesStatementResponse\x12&\n" +
	"\x0fdao_original_id\x18\x01 \x01(\tR\rdaoOriginalId\x121\n" +
	"\x04list\x18\x02 \x03(\v2\x1d.delegatepb.DelegateStatementR\x04list2\xb0\x02\n" +
	"\bDelegate\x12Q\n" +
	"\fGetDelegates\x12\x1f.delegatepb.GetDelegatesRequest\x1a .delegatepb.GetDelegatesResponse\x12c\n" +
	"\x12GetDelegateProfile\x12%.delegatepb.GetDelegateProfileRequest\x1a&.delegatepb.GetDelegateProfileResponse\x12l\n" +
	"\x15GetDelegatesStatement\x12(.delegatepb.GetDelegatesStatementRequest\x1a).delegatepb.GetDelegatesStatementResponseB\x0eZ\f./delegatepbb\x06proto3"

var (
	file_delegatepb_delegate_proto_rawDescOnce sync.Once
	file_delegatepb_delegate_proto_rawDescData []byte
)

func file_delegatepb_delegate_proto_rawDescGZIP() []byte {
	file_delegatepb_delegate_proto_rawDescOnce.Do(func() {
		file_delegatepb_delegate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delegatepb_delegate_proto_rawDesc), len(file_delegatepb_delegate_proto_rawDesc)))
	})
	return file_delegatepb_delegate_proto_rawDescData
}

var file_delegatepb_delegate_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_delegatepb_delegate_proto_goTypes = []any{
	(*DelegateEntry)(nil),                 // 0: delegatepb.DelegateEntry
	(*GetDelegatesRequest)(nil),           // 1: delegatepb.GetDelegatesRequest
	(*GetDelegatesResponse)(nil),          // 2: delegatepb.GetDelegatesResponse
	(*GetDelegateProfileRequest)(nil),     // 3: delegatepb.GetDelegateProfileRequest
	(*GetDelegateProfileResponse)(nil),    // 4: delegatepb.GetDelegateProfileResponse
	(*ProfileDelegateItem)(nil),           // 5: delegatepb.ProfileDelegateItem
	(*GetDelegatesStatementRequest)(nil),  // 6: delegatepb.GetDelegatesStatementRequest
	(*DelegateStatement)(nil),             // 7: delegatepb.DelegateStatement
	(*GetDelegatesStatementResponse)(nil), // 8: delegatepb.GetDelegatesStatementResponse
	(*anypb.Any)(nil),                     // 9: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
}
var file_delegatepb_delegate_proto_depIdxs = []int32{
	9,  // 0: delegatepb.GetDelegatesRequest.strategy:type_name -> google.protobuf.Any
	0,  // 1: delegatepb.GetDelegatesResponse.delegates:type_name -> delegatepb.DelegateEntry
	9,  // 2: delegatepb.GetDelegateProfileRequest.strategy:type_name -> google.protobuf.Any
	5,  // 3: delegatepb.GetDelegateProfileResponse.delegates:type_name -> delegatepb.ProfileDelegateItem
	10, // 4: delegatepb.GetDelegateProfileResponse.expiration:type_name -> google.protobuf.Timestamp
	7,  // 5: delegatepb.GetDelegatesStatementResponse.list:type_name -> delegatepb.DelegateStatement
	1,  // 6: delegatepb.Delegate.GetDelegates:input_type -> delegatepb.GetDelegatesRequest
	3,  // 7: delegatepb.Delegate.GetDelegateProfile:input_type -> delegatepb.GetDelegateProfileRequest
	6,  // 8: delegatepb.Delegate.GetDelegatesStatement:input_type -> delegatepb.GetDelegatesStatementRequest
	2,  // 9: delegatepb.Delegate.GetDelegates:output_type -> delegatepb.GetDelegatesResponse
	4,  // 10: delegatepb.Delegate.GetDelegateProfile:output_type -> delegatepb.GetDelegateProfileResponse
	8,  // 11: delegatepb.Delegate.GetDelegatesStatement:output_type -> delegatepb.GetDelegatesStatementResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_delegatepb_delegate_proto_init() }
func file_delegatepb_delegate_proto_init() {
	if File_delegatepb_delegate_proto != nil {
		return
	}
	file_delegatepb_delegate_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delegatepb_delegate_proto_rawDesc), len(file_delegatepb_delegate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delegatepb_delegate_proto_goTypes,
		DependencyIndexes: file_delegatepb_delegate_proto_depIdxs,
		MessageInfos:      file_delegatepb_delegate_proto_msgTypes,
	}.Build()
	File_delegatepb_delegate_proto = out.File
	file_delegatepb_delegate_proto_goTypes = nil
	file_delegatepb_delegate_proto_depIdxs = nil
}
