// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: delegatepb/delegate.proto

package delegatepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Delegate_GetDelegates_FullMethodName          = "/delegatepb.Delegate/GetDelegates"
	Delegate_GetDelegateProfile_FullMethodName    = "/delegatepb.Delegate/GetDelegateProfile"
	Delegate_GetDelegatesStatement_FullMethodName = "/delegatepb.Delegate/GetDelegatesStatement"
)

// DelegateClient is the client API for Delegate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DelegateClient interface {
	GetDelegates(ctx context.Context, in *GetDelegatesRequest, opts ...grpc.CallOption) (*GetDelegatesResponse, error)
	GetDelegateProfile(ctx context.Context, in *GetDelegateProfileRequest, opts ...grpc.CallOption) (*GetDelegateProfileResponse, error)
	GetDelegatesStatement(ctx context.Context, in *GetDelegatesStatementRequest, opts ...grpc.CallOption) (*GetDelegatesStatementResponse, error)
}

type delegateClient struct {
	cc grpc.ClientConnInterface
}

func NewDelegateClient(cc grpc.ClientConnInterface) DelegateClient {
	return &delegateClient{cc}
}

func (c *delegateClient) GetDelegates(ctx context.Context, in *GetDelegatesRequest, opts ...grpc.CallOption) (*GetDelegatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegatesResponse)
	err := c.cc.Invoke(ctx, Delegate_GetDelegates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegateClient) GetDelegateProfile(ctx context.Context, in *GetDelegateProfileRequest, opts ...grpc.CallOption) (*GetDelegateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegateProfileResponse)
	err := c.cc.Invoke(ctx, Delegate_GetDelegateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegateClient) GetDelegatesStatement(ctx context.Context, in *GetDelegatesStatementRequest, opts ...grpc.CallOption) (*GetDelegatesStatementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegatesStatementResponse)
	err := c.cc.Invoke(ctx, Delegate_GetDelegatesStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelegateServer is the server API for Delegate service.
// All implementations must embed UnimplementedDelegateServer
// for forward compatibility.
type DelegateServer interface {
	GetDelegates(context.Context, *GetDelegatesRequest) (*GetDelegatesResponse, error)
	GetDelegateProfile(context.Context, *GetDelegateProfileRequest) (*GetDelegateProfileResponse, error)
	GetDelegatesStatement(context.Context, *GetDelegatesStatementRequest) (*GetDelegatesStatementResponse, error)
	mustEmbedUnimplementedDelegateServer()
}

// UnimplementedDelegateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDelegateServer struct{}

func (UnimplementedDelegateServer) GetDelegates(context.Context, *GetDelegatesRequest) (*GetDelegatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelegates not implemented")
}
func (UnimplementedDelegateServer) GetDelegateProfile(context.Context, *GetDelegateProfileRequest) (*GetDelegateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelegateProfile not implemented")
}
func (UnimplementedDelegateServer) GetDelegatesStatement(context.Context, *GetDelegatesStatementRequest) (*GetDelegatesStatementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelegatesStatement not implemented")
}
func (UnimplementedDelegateServer) mustEmbedUnimplementedDelegateServer() {}
func (UnimplementedDelegateServer) testEmbeddedByValue()                  {}

// UnsafeDelegateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DelegateServer will
// result in compilation errors.
type UnsafeDelegateServer interface {
	mustEmbedUnimplementedDelegateServer()
}

func RegisterDelegateServer(s grpc.ServiceRegistrar, srv DelegateServer) {
	// If the following call panics, it indicates UnimplementedDelegateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Delegate_ServiceDesc, srv)
}

func _Delegate_GetDelegates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetDelegates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetDelegates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetDelegates(ctx, req.(*GetDelegatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delegate_GetDelegateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetDelegateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetDelegateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetDelegateProfile(ctx, req.(*GetDelegateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delegate_GetDelegatesStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegatesStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetDelegatesStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetDelegatesStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetDelegatesStatement(ctx, req.(*GetDelegatesStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Delegate_ServiceDesc is the grpc.ServiceDesc for Delegate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Delegate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delegatepb.Delegate",
	HandlerType: (*DelegateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDelegates",
			Handler:    _Delegate_GetDelegates_Handler,
		},
		{
			MethodName: "GetDelegateProfile",
			Handler:    _Delegate_GetDelegateProfile_Handler,
		},
		{
			MethodName: "GetDelegatesStatement",
			Handler:    _Delegate_GetDelegatesStatement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delegatepb/delegate.proto",
}
